version: '3.8'
services:
  web:
    image: odoo:12
    user: "root"
    command: "/mnt/extra-addons/run.sh"
    depends_on:
      - db
    links:
      - "mssql"
    ports:
      - "8070:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config/odoo:/etc/odoo
      - ./:/mnt/extra-addons
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
  mssql:
    image: mcr.microsoft.com/mssql/server
    environment: 
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=P@ssw0rd"
      - "MSSQL_PID=Developer"
    ports:
      - "1433:1433"
    volumes:
      - odoo-mssql-data:/var/opt/mssql
  adminer:
    image: adminer
    links:
      - "mssql"
      - "db"
    ports:
      - "8080:8080"
volumes:
  odoo-web-data:
  odoo-db-data:
  odoo-mssql-data: